#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odx.Demo.Model
{
	
	
	/// <summary>
	/// Type of activity.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum activitypointer_activitytypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamschat = 10099,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InviteRedemption = 10244,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortalComment = 10245,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuickCampaign = 4406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignActivity = 4402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignResponse = 4401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CaseResolution = 4206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityClose = 4208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrderClose = 4209,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteClose = 4211,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicealert = 10514,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyinvite = 10524,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyresponse = 10526,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotTranscript = 10560,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversation = 10636,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Session = 10653,
	}
}
#pragma warning restore CS1591
