#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odx.Demo.Model
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum mobileofflineenabledentities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Note = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueItem = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAKPIInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityFileAttachment = 10098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleImage = 10107,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleAttachment = 10113,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncFnoState = 10132,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncState = 10133,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountLeads = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContactLeads = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lead = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Product = 1024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Property = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyAssociation = 1235,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyOptionSetItem = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceList = 1022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceListItem = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductRelationship = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unit = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnitGroup = 1056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entitlement = 9700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementContact = 7272,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementProduct = 6363,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementTemplateProduct = 4545,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentKnowledgeBaseRecord = 9931,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneToCaseProcess = 952,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connection = 3234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRole = 3231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlert = 10321,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDevice = 10322,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCategory = 10323,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCommand = 10324,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCommandDefinition = 10325,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceDataHistory = 10326,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceProperty = 10327,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceRegistrationHistory = 10328,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTPropertyDefinition = 10331,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTProvider = 10332,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTProviderInstance = 10333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTSettings = 10334,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlerttoCaseProcess = 10337,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorAddress = 1004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorProduct = 1006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadCompetitors = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadProduct = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadToOpportunitySalesProcess = 954,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opportunity = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityCompetitors = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityProduct = 1083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunitySalesProcess = 953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Competitor = 123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyInstance = 1333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invoice = 1090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvoiceProduct = 1091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quote = 1084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteProduct = 1085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Order = 1088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrderProduct = 1089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Currency = 9105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityAttachment = 10593,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Meeting = 4201,
	}
}
#pragma warning restore CS1591
