#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odx.Demo.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_channelmessageparttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		plaintext = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		html = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		url = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		binary = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		image = 192350004,
	}
}
#pragma warning restore CS1591
