#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odx.Demo.Model
{
	
	
	/// <summary>
	/// Survey Mode
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_postconversationsurveymode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Insertsurveyinconversation = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sendsurveylinktoconversation = 192350001,
	}
}
#pragma warning restore CS1591
