#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odx.Demo.Model
{
	
	
	/// <summary>
	/// Type of attachment.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_attachmenttype
	{
		
		/// <summary>
		/// Image attachment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Image = 700610000,
		
		/// <summary>
		/// Video attachment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Video = 700610001,
	}
}
#pragma warning restore CS1591
