#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Odx.Demo.MultipleEvents.Common.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class DataverseContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public DataverseContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Odx.Demo.MultipleEvents.Common.Model.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Odx.Demo.MultipleEvents.Common.Model.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<Odx.Demo.MultipleEvents.Common.Model.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Odx.Demo.MultipleEvents.Common.Model.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Odx.Demo.MultipleEvents.Common.Model.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<Odx.Demo.MultipleEvents.Common.Model.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Odx.Demo.MultipleEvents.Common.Model.Task"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Odx.Demo.MultipleEvents.Common.Model.Task> TaskSet
		{
			get
			{
				return this.CreateQuery<Odx.Demo.MultipleEvents.Common.Model.Task>();
			}
		}
	}
}
#pragma warning restore CS1591
